name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: GitHub Actions - Updated readme stats (automatic)
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_EDITORS: "True"




      

